# Generated by Django 2.2.6 on 2019-12-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('album_title', models.CharField(max_length=250)),
                ('album_genre', models.CharField(max_length=100)),
                ('album_logo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=200)),
                ('file_type', models.CharField(max_length=200)),
                ('album', models.ForeignKey(on_delete='CASCADE', to='Music.Album')),
            ],
        ),
    ]
